### ISSUE TITLE
Wallet not showing transferred tokens 

### ISSUE THREAD

**Issue by isauditor** [vericoin/vericoin-oldrepo#67]
Hello, On November 12, 2017 I transferred some VRC tokens from an Exchange to my Vericoin desktop wallet version 1.6.5.5. The transaction was successful but I do not see tokens in my wallet balance even though wallet is showing it is in  sync. Please help. Thanks.

**Comment by vericoin** [comment]
Make sure you have connections, come here for support slack.vericoin.info
