### ISSUE TITLE
Issues installing wallet on Ubuntu

### ISSUE THREAD

**Issue by RustyTemper** [vericoin/vericoin-oldrepo#74]
Having issues installing Ubuntu and I'm getting this error:

Package libdb4.8++-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Can anyone help?

**Comment by itsN1X** [comment]
@RustyTemper 
try `sudo apt install -f` and then build again, maybe.
---
Also:
 - [ ] see if libpcre16-3 is present.
 - [ ] Its a common bug on 16.04 // 14.04 ; See if you could get a canonical 1X.10 image installed, maybe, and make a run in the `--fix-broken` mode.
cc // @vericoin @effectsToCause

**Comment by RustyTemper** [comment]
I’m still new to Ubuntu and I don’t know what you mean. Would you mind giving me quick instructions? I apologise for the inconvenience.

**Comment by itsN1X** [comment]
@RustyTemper 

 - Are you sudo // root logged-on?

 - what distribution of ubuntu are you working from? ubuntu16.10 ^64-bit is the recommended (basic-ease) OS for vericoin, personally-speaking. Once youre comfortable there, you could move into using debian for make'ing ```vericoind``` and the runtime more efficient!
 - generally-speaking, try this one-liner in your terminal :: 

```
sudo apt-get install git libboost-dev libboost-system-dev libboost-filesystem-dev libboost-program-options-dev libboost-thread-dev libpcre16-3 libssl-dev libdb++-dev libminiupnpc-dev libboost-all-dev libqrencode-dev git libcurl4-gnutls-dev libminizip-dev && echo "COOL! Dependencies installed succesfully, Rusty!"
```

When you get the 'COOL' message, download the [vericoin wallet](http://www.vericoin.info/downloads/VeriCoin_1.7_64bit.run) and the [Verium Wallet cum Vault - Miner](http://www.vericoin.info/downloads/Verium_1.1_64bit.run) then hit up your terminal again -- this time do :: 
```
cd ..
cd /Downloads/
chmod +x VeriCoin_1.7_64bit.run
chmod +x Verium_1.1_64bit.run
```

Now, hitting left-mouse twice would prompt you to execute these files, do select 'execute' both the times, for either piece of software.


 - depending on your system power // speed // RAM ?? cores && CPU // GPU,  >>WAIT-patiently<< and your silicon should be running the off-blue Verium Dual-Chain software "successfully" !

---

Do let me know -- about how it unfolds!
& Welcome to the community ( X

**Comment by RustyTemper** [comment]
Thank you for the support, it's appreciated. Now:

- I am logged on as root
- I am using Ubuntu 16.04 64-bit
- I tried the "one liner" you suggested and I'm getting "E: Unable to locate package libdb4build-essential"

What am I missing here?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by itsN1X** [comment]
Oh, sorry my bad, wrote that twice as essn. & dev. ppa'ed both :face_with_head_bandage: 
try this after the one-liner > I re-edited it again <
```
sudo apt-get install --fix-broken
```
& see if you can move to ubuntu 14.10 or 16.10

**Comment by RustyTemper** [comment]
I am getting this with the command:
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.

When I use the "one liner" I'm getting the same error.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by itsN1X** [comment]
Kay wait::
1 Try ```sudo apt-get install libdb++-dev``` & it'd return this ::
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libdb5.3++ libdb5.3++-dev libdb5.3-dev
Suggested packages:
  db5.3-doc
The following NEW packages will be installed:
  libdb++-dev libdb5.3++ libdb5.3++-dev libdb5.3-dev
0 upgraded, 4 newly installed, 0 to remove and 91 not upgraded.
Need to get 2246 kB of archives.
After this operation, 8395 kB of additional disk space will be used.
Do you want to continue? [Y/n] >hit Y<
```

3. ```sudo apt-get install git libboost-dev libboost-system-dev libboost-filesystem-dev libboost-program-options-dev libboost-thread-dev libpcre16-3 libssl-dev libminiupnpc-dev libboost-all-dev libqrencode-dev git libcurl4-gnutls-dev libminizip-dev && echo "COOL! Dependencies installed succesfully, Rusty!"```

4. Down the loads from vericoin.info and move into the /Downloads/ directory (with sudo // root priv.)

5. Convert them to executables and execute (btw, did you try to build from github.com/vericoin/vericoin directly? )

6. If this don't work, I promise I'd be back in Office after dinner and write you a special post with vid/gif/png's. Also I'll have the stable *.run files & I'd personally mirror them and re-validate + re-check all-of-this.

---

Thanks for thy patience, @RustyTemper ru ( :

###### Is anyone else here ? @vericoin 
@vericoin vericoin / vericoin
@apkcoin apkcoin / vericoin
@bankonme bankonme / vericoin
@cryptocoinsourcecode cryptocoinsourcecode / vericoin
@cryptocurrent cryptocurrent / vericoin
@benzhi888 benzhi888 / renminbi
@cc5985 cc5985 / vericoin
@crackfoo crackfoo / vericoin
@dmoody256 dmoody256 / vericoin
@effectsToCause effectsToCause / vericoin
@hoangduit hoangduit / vericoin
@inaciocarozzi inaciocarozzi / vericoin
@kernelpanik23 kernelpanik23 / vericoin
@Lisk115 Lisk115 / vericoin
@ohiTuna ohiTuna / vericoin
@pnosker pnosker / vericoin
@rolandoalvarado rolandoalvarado / vericoin
@sitemagik sitemagik / swz
@tmli3b3rm4n tmli3b3rm4n / vericoin
@VeriumReserve VeriumReserve / verium
@1a1a11a 1a1a11a / verium
@CloudMining CloudMining / verium
@ComputerCraftr ComputerCraftr / verium
@DJoeDt DJoeDt / verium-1
@HashPool HashPool / verium
@hd4r hd4r / verium
@howardsiv howardsiv / verium
@InflatibleYoshi InflatibleYoshi / verium
@Jiloc Jiloc / verium
@kentoeng kentoeng / verium
@krisklosterman krisklosterman / verium
@xg427 xg427 / verium
@lanbetatester lanbetatester / verium
@npwalker npwalker / verium
@phoneman13 phoneman13 / verium
@rkanadev rkanadev / verium
@robin-thomas robin-thomas / verium
@shyrwall shyrwall / verium
@uniescie uniescie / verium
@x314network x314network / verium

**Comment by RustyTemper** [comment]
Ok, so far so good. I'll update you along the way. Thanks!

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by RustyTemper** [comment]
I made it past step 3 but I'm stuck on step 4:

4. I go to vericoin.info and click download for linux 64-bit. A page full of script loads but is unresponsive to the download. Is it supposed to automatically download after clicking "download"?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by itsN1X** [comment]
OH! save that with your right-mouse-button @RustyTemper for a :100: %

**Comment by RustyTemper** [comment]
Lol, that makes sense :)
So I downloaded the client but I'm not too sure what to do from there.
I don't understand steps 5 and beyond.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by itsN1X** [comment]
> (#74(comment))

download the vericoin wallet and the Verium Wallet cum Vault - Miner then hit up your terminal again -- this time do ::

cd ..
cd /Downloads/
chmod +x VeriCoin_1.7_64bit.run
chmod +x Verium_1.1_64bit.run

Now, hitting left-mouse twice would prompt you to execute these files, do select 'execute' both the times, for either piece of software.

**Comment by RustyTemper** [comment]
Hey there! Happy new year! Sorry for the late reply, I had a little family vacation :)
Anyway, I executed these two commands --
chmod +x VeriCoin_1.7_64bit.run
chmod +x Verium_1.1_64bit.run
Nothing happens. The files I downloaded in are still the
"VeriCoin_1.7_64bit.run" file. I double click left mouse and I'm prompted with pypar2 window.
I don't think this is supposed to happen, correct?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by jdgraff** [comment]
I have been mining verium on a W7 box for a few months, but want to move to a supermicro board running Ubuntu 16.04.  

I have Verium cpu_miner installed and and have been attempting to get Vericoin Wallet installed. I have run your oneliner, but when I execute VeriCoin_1.7_64bit.run I get some OpenGL errors culminating in vericoin runaway exception, any suggestions would be appreciated:

![wallet_errors](https://user-images.githubusercontent.com/3837563/34635065-163a5290-f250-11e7-80cd-8cc733af7060.png)

**Comment by ghost** [comment]
Hi @RustyTemper, sorry if I'm butting in here...

I'm using Linux Mint 18.3, which is an Ubuntu variant. I never had any problems running Verium_1.1_64bit.run so I did some googling and found others with the pypar2 thing. Somehow, it looks like Ubuntu still thinks you don't have the right to execute the file.

Maybe the file browser is still a regular "user" trying to run a "root" program?

Can you just go to the command line and try it. Here's what I do:

```
/Downloads $ chmod 755 Verium_1.1_64bit.run
/Downloads $ ls -alh
total 75404
drwxr-xr-x  3 mark mark     4096 Jan  5 17:34 ./
drwxr-xr-x 15 mark mark     4096 Jan  5 17:34 ../
drwxrwxr-x  5 mark mark     4096 Oct 26 10:57 Verium_1.1_64bit/
-rwxr-xr-x  1 mark mark 77199027 Jan  5 17:34 Verium_1.1_64bit.run*
mark@xps-mint ~/Downloads $ 
```
See all the 'x' es? That indicates that the file is executable for all users.

then I just run it:

/Downloads $ ./Verium1.1_64bit.run

It does ask for my password since I'm not logged in as root, but after that it always installs and runs just fine. (I've never had to install any dependencies, unless I'm building it - which you're not).

See if that helps!

**Comment by jdgraff** [comment]
thank you for your suggestion,  I have 3 x's for VeriCoin_1.7_64bit.run permissioins.  I am not using sudo and am not root.  There was a post recently by on the Vericoin forum where it seemed the conclusion was not to run that file as root.

I am running it via a vnc connection but I have also tried it via the local gui, I do not know if the vnc connection might have something to do with it?

**Comment by whompy** [comment]
What graphics driver/hardware are you using? Looks like a GL error.

**Comment by jdgraff** [comment]
The board is a Supermicro A1sri 2758-f, Intel says their graphics drivers are included in Linux distributions but I do not know how to verify they are installed.

**Comment by whompy** [comment]
Should be included in Mesa packages that would provide libgl. Which distro are you using?

**Comment by jdgraff** [comment]
I am on Ubuntu 16.04,  

I am mining now.  Seems like  the one liner above with a reboot may have helped.  I do have to run verium-qt as root.

Also discovered an issued with tightvnc not handling keyboard input properly with qt, Ultravnc is believed to work but have not tested that yet.  Using the local gui currently.

**Comment by itsN1X** [comment]
Have you patched-up your 16.04 to the new years' CVE antidote?
Cheers on your working setup @jdgraff !

**Comment by whompy** [comment]
Rather than running as root, have you tried adding the user to the video group?

**Comment by RustyTemper** [comment]
I have tried executing the commands and tried to run the file. Nothing happens. This is frustrating, what am I doing wrong?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by itsN1X** [comment]
Idk if this is the right place to say this, but wait for a few  more days -- A ew prod. release should be out soon. Also I myself have been testing-cum-developing a better qt alt. to the verium miner-cum-wallet, and hope to release before 14th of Feb. It has a few notable improvs.
- [ ]  Prune
- [ ]  Faster sync employing additional peers.
- [ ]  More nodes ( I'mspreading it!)
---
If you happen to find the core-commitee of this project, do let me know :: Meanwhile I can setup a discord // IRC // Slack for us (Everyone is invited!)and we'd discuss the config. + installation there.
Do close this issue OP, and I'll file in anew issue regarding the community addressal system.
If you really believe in this dual chain PosT schema, we all will rule the $crypto ! 
And please patch your OS, and watch the JamesBond017 Spectre.!
Cheers
Xeno

**Comment by effectsToCause** [comment]
Hey guys, playing catch up on these issues.  Are you all sorted yet or no?

**Comment by effectsToCause** [comment]
Generally techsupport is most well supported in our slack.vericoin.info #techsupport channel, issues are normally intended for code issue themselves not troubleshooting as much, but if you get help here too that's fine also.

**Comment by whompy** [comment]
Still no luck compiling. There's a workaround to use an old version of
libssl on Debian, but no detail on what version or why. This makes it hard
for me to find a similar fix for Arch Linux.

**Comment by jdgraff** [comment]
I have tried adding my mining user to the video group but i still get the error when I launch verium-qt, currently the only solution seems to be to start it as root.
