### ISSUE TITLE
Core Dump after approx. 24 hours

### ISSUE THREAD

**Issue by whompy** [vericoin/vericoin-oldrepo#76]
So running the 1.7 release, I can never succeed in staking as this happens after running for a day or so. Note that I am presently mining sumokoin on this machine as well, so the CPU is under load.

libpng warning: iCCP: known incorrect sRGB profile
qt.network.ssl: QSslSocket: cannot resolve SSLv2_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv2_server_method
QObject::connect: No such slot TransactionView::showTotalAmount(reset)
QObject::connect: No such slot TransactionView::showTotalAmount(reset)
QObject::connect: No such slot TransactionView::showTotalAmount(reset)
QObject::connect: No such slot TransactionView::showTotalAmount(reset)
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile

************************
EXCEPTION: St9bad_alloc       
std::bad_alloc       
vericoin in ThreadMessageHandler()       

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

[1]  + abort (core dumped)  ./vericoin-qt --quiet

**Comment by effectsToCause** [comment]
Hi whompy,

it looks like you are running out of memory
try adding this to conf file
maxconnections=10
This can prevent a spike in memory usage due to many nodes connecting

**Comment by whompy** [comment]
Okay. I just dropped the connections to 20 and still had issues. I'll try
10.

**Comment by effectsToCause** [comment]
you can also try adding more swap space or virtual memory to your system

**Comment by whompy** [comment]
Added swap to a system with 16GB RAM already, and it bombed out once again.
I'm giving up on trying to use this version of the software and will test
back next release.

**Comment by effectsToCause** [comment]
This should now be fixed where the ram usage is consistently near the size of the blockchain, I've reduced max connections in the code and how many blocks are passed between nodes at any given time.  Upon 0.16 bitcoin core blockchain code base port version this will again drop to around 350MB
