### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by vikramdurai** [vericoin/vericoin-oldrepo#83]
Please build a Docker image, it would be really cool :)

**Comment by dennisvanderpool** [comment]
I will give it a try :)

**Comment by vikramdurai** [comment]
Any progress on the Docker image?
Basically docker wraps all dependencies and code into one independent container that can run anywhere Docker runs.

**Comment by dennisvanderpool** [comment]
Yeah, i build it and made a pull request for it. Somebody else already created a docker image, which seems to have more features (docker-compose file): https://hub.docker.com/r/buluba89/vericoind/

**Comment by dennisvanderpool** [comment]
And here is my pull request for my Dockerfile, i'm running this currently, built it 2 weeks ago:
https://github.com/vericoin/vericoin/pull/5

**Comment by effectsToCause** [comment]
thanks merged

**Comment by vikramdurai** [comment]
closed
